services:
  - type: web
    name: pdf-to-excel-converter
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y poppler-utils && 
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    plan: free